trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      git config user.name "MWG Bot 🤖"
      git config user.email "cloud@mwg.digital"
    displayName: "Setup Git client"

  - script: git remote add GitHub $GITHUB_GIT_URL
    displayName: "Add GitHub repository"
    env:
      GITHUB_GIT_URL: $(GITHUB_GIT_URL)

  - script: |
      git -c http.extraHeader="Authorization: Basic $GITHUB_TOKEN" pull GitHub HEAD:$BRANCH_NAME
      git -c http.extraHeader="Authorization: Basic $GITHUB_TOKEN" push --set-upstream GitHub HEAD:$BRANCH_NAME
      git -c http.extraHeader="Authorization: Basic $GITHUB_TOKEN" push GitHub --tags
    displayName: "Commit and push to GitHub Git"
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      BRANCH_NAME: $(GITHUB_BRANCH_NAME)
