trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      git config user.name "MWG Bot 🤖"
      git config user.email "cloud@mwg.digital"
    displayName: "Setup Git client"

  - script: |
      git config credential.helper 'store --file=.git-credentials'
      echo "https://<token>:x-oauth-basic@github.com" > .git-credentials
    displayName: "Add GitHub repository"
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - script: |
      git push origin main
    displayName: "Commit and push to GitHub Git"
